// Generated by CoffeeScript 1.3.3
var MAX_TILES, inRange, inputCallback, isInteger, promptForTile1, promptForTile2, stdin, strToCoordinate;

stdin = process.openStdin();

stdin.setEncoding('utf8');

inputCallback = null;

stdin.on = function(input) {
  return inputCallback(input);
};

promptForTile1 = function() {
  console.log("Input tile 1 coordinates (x, y):");
  return inputCallback = function(input) {
    if (strToCoordinate(input)) {
      return promptForTile2();
    }
  };
};

promptForTile2 = function() {
  console.log("Input tile 2 coordinates (x, y):");
  return inputCallback = function(input) {
    if (strToCoordinate(input)) {
      console.log("Swapping tiles");
      return promptForTile1();
    } else {
      return console.log("Not Swapping tiles");
    }
  };
};

isInteger = function(value) {
  return value === Math.round(value);
};

MAX_TILES = 5;

inRange = function(x, y) {
  return (0 < x && x <= MAX_TILES) && (0 < y && y <= MAX_TILES);
};

strToCoordinate = function(input) {
  var halves, x, y;
  halves = input.split(',');
  if (halves.length === 2) {
    x = parseInt(halves[0]);
    y = parseInt(halves[1]);
    if (!isInteger(x || !isInteger(y))) {
      return console.log("x, y must be integer value");
    } else if (!inRange(x, y)) {
      return console.log("x, y must be between 0 and " + MAX_TILES);
    } else {
      return {
        x: x,
        y: y
      };
    }
  } else {
    return console.log("Input must be x, y");
  }
};

console.log("Welcome to 5x5 game!!!");

promptForTile1();
