// Generated by CoffeeScript 1.3.3
var Grid, alphabet, count, elem, fs, letter, randomLetter, regex, root, tileCounts, tileCountsMatched, tileValues, tilesPoint, totalTiles, _fn, _i, _len;

fs = require('fs');

tilesPoint = fs.readFileSync('tilecount.txt', 'utf8');

regex = /^(\w)\s(\d+)\s(\d+)/mg;

tileCountsMatched = tilesPoint.match(regex);

tileCounts = {};

tileValues = {};

_fn = function(elem) {
  var mychar, probabilities, value, _ref;
  _ref = elem.split(' '), mychar = _ref[0], probabilities = _ref[1], value = _ref[2];
  tileCounts[mychar] = parseInt(probabilities);
  return tileValues[mychar] = parseInt(value);
};
for (_i = 0, _len = tileCountsMatched.length; _i < _len; _i++) {
  elem = tileCountsMatched[_i];
  _fn(elem);
}

totalTiles = 0;

for (letter in tileCounts) {
  count = tileCounts[letter];
  totalTiles += count;
}

alphabet = ((function() {
  var _results;
  _results = [];
  for (letter in tileCounts) {
    _results.push(letter);
  }
  return _results;
})()).sort();

randomLetter = function() {
  var randomNumber, x, _j, _len1;
  randomNumber = Math.ceil(Math.random() * totalTiles);
  x = 1;
  for (_j = 0, _len1 = alphabet.length; _j < _len1; _j++) {
    letter = alphabet[_j];
    x += tileCounts[letter];
    if (x > randomNumber) {
      return letter;
    }
  }
};

Grid = (function() {

  function Grid() {
    var size, x, y;
    this.size = size = 5;
    this.tiles = (function() {
      var _j, _ref, _results;
      _results = [];
      for (x = _j = 0, _ref = this.size; 0 <= _ref ? _j < _ref : _j > _ref; x = 0 <= _ref ? ++_j : --_j) {
        _results.push((function() {
          var _k, _ref1, _results1;
          _results1 = [];
          for (y = _k = 0, _ref1 = this.size; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; y = 0 <= _ref1 ? ++_k : --_k) {
            _results1.push(randomLetter());
          }
          return _results1;
        }).call(this));
      }
      return _results;
    }).call(this);
  }

  Grid.prototype.inRange = function(x, y) {
    return (0 <= x && x < this.size) && (0 <= y && y < this.size);
  };

  Grid.prototype.swap = function(_arg) {
    var x1, x2, y1, y2, _ref;
    x1 = _arg.x1, y1 = _arg.y1, x2 = _arg.x2, y2 = _arg.y2;
    return _ref = [this.tiles[x2][y2], this.tiles[x1][y1]], this.tiles[x1][y1] = _ref[0], this.tiles[x2][y2] = _ref[1], _ref;
  };

  Grid.prototype.rows = function() {
    var x, y, _j, _ref, _results;
    _results = [];
    for (x = _j = 0, _ref = this.size; 0 <= _ref ? _j < _ref : _j > _ref; x = 0 <= _ref ? ++_j : --_j) {
      _results.push((function() {
        var _k, _ref1, _results1;
        _results1 = [];
        for (y = _k = 0, _ref1 = this.size; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; y = 0 <= _ref1 ? ++_k : --_k) {
          _results1.push(this.tiles[y][x]);
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  return Grid;

})();

root = typeof exports !== "undefined" && exports !== null ? exports : window;

root.Grid = Grid;

root.tileValues = tileValues;
