// Generated by CoffeeScript 1.3.3
(function() {
  var Dictionary, Grid, OWL2, OWL2Definitions, Player, currPlayer, dictionary, getDefintion, grid, inputCallback, isInteger, newGame, player1, player2, printGrid, promptForTile1, promptForTile2, stdin, strToCoordinates;

  Dictionary = require('./Dictionary').Dictionary;

  Grid = require('./Grid').Grid;

  Player = require('./Player').Player;

  OWL2 = require('./OWL2').OWL2;

  OWL2Definitions = require('./OWL2Definitions').OWL2Definitions;

  grid = dictionary = currPlayer = player1 = player2 = null;

  isInteger = function(value) {
    return value === Math.round(value);
  };

  printGrid = function() {
    var i, row, rowSeparator, rowStrings, rows;
    rows = grid.rows();
    rowStrings = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        row = rows[_i];
        _results.push(' ' + row.join(' | '));
      }
      return _results;
    })();
    rowSeparator = ((function() {
      var _i, _ref, _results;
      _results = [];
      for (i = _i = 1, _ref = GRID_SIZE * 4; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
        _results.push('-');
      }
      return _results;
    })()).join('');
    return console.log('\n' + rowStrings.join("\n" + rowSeparator + "\n") + '\n');
  };

  getDefintion = function(word) {
    var match, see, _ref;
    match = (_ref = OWL2Definitions[word]) != null ? _ref.match(/<(\w+)=\w>/) : void 0;
    if (match) {
      see = match[1];
      return OWL2Definitions[word] + ("see: " + see + " -> ") + OWL2Definitions[see.toUpperCase()];
    } else {
      return OWL2Definitions[word];
    }
  };

  strToCoordinates = function(input) {
    var halves, x, y;
    halves = input.split(',');
    if (halves.length === 2) {
      x = parseInt(halves[0]);
      y = parseInt(halves[1]);
      if (!isInteger(x || !isInteger(y))) {
        return console.log("x, y must be integer value");
      } else if (!inRange(x - 1, y - 1)) {
        return console.log("x, y must be between 0 and " + MAX_TILES);
      } else {
        return {
          x: x,
          y: y
        };
      }
    } else {
      return console.log("Input must be x, y");
    }
  };

  stdin = process.openStdin();

  stdin.setEncoding('utf8');

  inputCallback = null;

  stdin.on('data', function(input) {
    return inputCallback(input);
  });

  promptForTile1 = function() {
    printGrid();
    console.log("" + currPlayer + ", Input tile 1 coordinates (x, y):");
    return inputCallback = function(input) {
      var x, y, _ref;
      try {
        _ref = strToCoordinates(input), x = _ref.x, y = _ref.y;
      } catch (e) {
        console.log(e);
        return;
      }
      return promptForTile2(x, y);
    };
  };

  promptForTile2 = function(x1, y1) {
    console.log("" + currPlayer + ", Input tile 2 coordinates (x, y):");
    return inputCallback = function(input) {
      var moveScore, newWords, word, x2, y2, _i, _len, _ref, _ref1;
      try {
        _ref = strToCoordinates(input), x2 = _ref.x, y2 = _ref.y;
      } catch (e) {
        console.log(e);
        return;
      }
      if (x1 === x2 && y1 === y2) {
        return console.log("swap different tiles please");
      } else {
        console.log("swapping: (" + x1 + "," + y1 + ") \"" + grid[x1 - 1][y1 - 1] + "\" with (" + x2 + "," + y2 + ") \"" + grid[x2 - 1][y2 - 1] + "\"");
        x1--;
        x2--;
        y1--;
        y2--;
        _ref1 = currPlayer.makeMove({
          x1: x1,
          y1: y1,
          x2: x2,
          y2: y2
        }), moveScore = _ref1.moveScore, newWords = _ref1.newWords;
        if (moveScore !== 0) {
          console.log("" + currPlayer + " formed the following " + newWords.length + " word(s)\n" + (newWords.join(', ')) + "\nearning " + (moveScore / newWords.length) + "x" + newWords.length + " = " + moveScore + " points");
          for (_i = 0, _len = newWords.length; _i < _len; _i++) {
            word = newWords[_i];
            console.log("" + word + ": " + (getDefintion(word)));
          }
          console.log("" + currPlayer + "'s score after " + currPlayer.moveCount + " moves: " + currPlayer.score);
        }
        console.log("You score after " + moveCount + " moves: " + score);
        currPlayer = currPlayer === player1 ? player2 : player1;
        return promptForTile1();
      }
    };
  };

  newGame = function() {
    grid = new Grid;
    dictionary = new Dictionary(OWL2, grid);
    currPlayer = player1 = new Player('Player 1', dictionary);
    player2 = new Player('Player 2', dictionary);
    console.log("Welcome to 5x5!");
    if (dictionary.usedWords.length !== 0) {
      console.log("Initially used words:\n" + (dictionary.usedWords.join(', ')) + "	  ");
    }
    return promptForTile1();
  };

  newGame();

}).call(this);
