// Generated by CoffeeScript 1.3.3
var array, i, key, maximum, object, pos, title, value, _i, _j, _k, _len, _len1, _ref, _ref1,
  __hasProp = {}.hasOwnProperty;

title = function(text) {
  var i, line, _i, _ref;
  console.log(" ");
  console.log(text);
  line = "";
  for (i = _i = 0, _ref = text.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    line += "=";
  }
  return console.log(line);
};

object = {
  id: 1,
  firstname: 'Sébastien',
  lastname: 'Barbieri'
};

title("for key, value of object");

for (key in object) {
  value = object[key];
  console.log("key: " + key + " value: " + value);
}

title("for key of object");

for (key in object) {
  console.log("key: " + key + " object." + key + ": " + object[key]);
}

title("own key");

for (key in object) {
  if (!__hasProp.call(object, key)) continue;
  console.log("key: " + key + " object." + key + ": " + object[key]);
}

title("arrays");

array = [1, 2, 3, 4, 5, 6, 7, 8, 9];

for (_i = 0, _len = array.length; _i < _len; _i++) {
  value = array[_i];
  console.log("Array value: " + value);
}

title("loop checks for string with when");

for (key in object) {
  value = object[key];
  if (typeof value === 'string') {
    console.log("" + key + " is a string containing " + value);
  }
}

title("for in by");

for (pos = _j = 0, _ref = 1 / 3; _j <= 3; pos = _j += _ref) {
  console.log(pos);
}

title("maximum");

maximum = 0;

_ref1 = [1, 5, 65, 23, 10, 32];
for (_k = 0, _len1 = _ref1.length; _k < _len1; _k++) {
  i = _ref1[_k];
  if (i > maximum) {
    maximum = i;
  }
}

console.log("maximum: " + maximum);
